server:
  port: 8087

spring:
  application:
    name: ms-mensajeria

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

twilio:
  account-sid:
  auth-token:
  phone-number:
